name: Hello_world

on:
  push:
    branches:
      - main

jobs:
  say_hello:
    runs-on: ubuntu-latest # the environment
    
    steps:
      - name: this is first step
        run: echo "Hello world"

      - name: Checkout repsitory
        uses: actions/checkout@v4.2.2

      - name: listing all files
        run: ls -la
        
